export const FOUR_BOOKS = [
  {
    id: "classroom",
    name: "Classroom seven",
    asof: "Always",
    job: "Teaches the four rooms. Not a ticket pad.",
    href: "/jobs",
  },
  {
    id: "live",
    name: "Live ISA · 17 lines",
    asof: "T212 · 16 Sep 09:46 · weights only",
    job: "The pad is the lock. Prime II live. Cash residual not published.",
    href: "/house",
  },
  {
    id: "prime",
    name: "Invictus Prime I · 15 lines",
    asof: "Archived 7 Sep 2026, 23:08 BST",
    job: "Predecessor lock. IGLS + INXG on probation. Gold 9.6 named floor breach. Kept as history.",
    href: "/house",
  },
  {
    id: "draft",
    name: "Machine draft · 16 lines",
    asof: "12 Sep 2026, 16:55 BST · superseded",
    job: "45% engine teaching pie. Superseded by Prime II as the lock. Still the interactive machine.",
    href: "/learn/machine",
  },
  {
    id: "prime2",
    name: "Invictus Prime II · lock",
    asof: "Locked 16 Sep 2026, 09:46 BST",
    job: "House lock = T212 print. WNRG, IWVL, FLOT, DBMF live. VAGS + IDTL sold. 17 lines. Gold wrapper IGLN.",
    href: "/house",
  },
] as const;

export const LEARN_TRACKS = [
  {
    id: "rooms",
    title: "Four rooms",
    body: "Toggle growth and inflation. Watch who earns and who suffers. The machine does not need the next regime named.",
    href: "/learn/machine",
    label: "OPEN MACHINE",
  },
  {
    id: "jobs",
    title: "Ticker atlas",
    body: "Every line is a sentence: job, farm role, 2022, partners when it suffers. Draft pie and Prime weights live side by side in the library.",
    href: "/learn/atlas",
    label: "OPEN ATLAS",
  },
  {
    id: "library",
    title: "Library",
    body: "Search the whole desk. Cards, tickers, years, gates. The knowledge graph.",
    href: "/learn/library",
    label: "OPEN LIBRARY",
  },
  {
    id: "years",
    title: "Year book",
    body: "2008 trough. 2013 invoice. 2022 proof. 2025 surprise. 9 Sep overlay. Score the sleeve against its contract.",
    href: "/learn/years",
    label: "OPEN YEARS",
  },
  {
    id: "prime2",
    title: "Prime II",
    body: "House lock. Derrick, value tilt, float. 17 listed. Pad still 14. Count the lines before you praise the OCF.",
    href: "/learn/prime2",
    label: "OPEN PRIME II",
  },
  {
    id: "universe",
    title: "Universe screen",
    body: "Five filters. Thirty tickers. Rank is a screen, not a ticket. WNRG is loud. IWVL can absorb. FLOT is a gate.",
    href: "/learn/universe",
    label: "OPEN UNIVERSE",
  },
  {
    id: "derrick",
    title: "WNRG vs IOGP",
    body: "Integrated majors versus 98% E&P. Almost no holdings overlap. The derrick is not the well.",
    href: "/learn/derrick",
    label: "OPEN DERRICK",
  },
  {
    id: "protocol",
    title: "The protocol",
    body: "Should I sell. Has walk-back fired. May I add a 17th line. Size gates. Permanently dead ideas.",
    href: "/learn/decide",
    label: "OPEN DECIDE",
  },
  {
    id: "path",
    title: "Thirty years",
    body: "Plan around 5%. Work from 7.5%. Do not plan around history. The debit is the lever.",
    href: "/learn/path",
    label: "OPEN PATH",
  },
  {
    id: "drills",
    title: "Drills",
    body: "Twenty questions. Rooms, jobs, walk-back, Prime II count, the derrick, the float. Progress stays on this device.",
    href: "/learn/quiz",
    label: "SIT THE DRILL",
  },
  {
    id: "listen",
    title: "Two-desk series",
    body: "Atlas and Rigel. Seasons 0–3. Prime II lock tape on 15–18. Jobs before tickers.",
    href: "/listen",
    label: "LISTEN",
  },
];

export const GLOSSARY: { term: string; group: string; def: string }[] = [
  { term: "Four rooms", group: "Machine", def: "Growth up/down × inflation up/down. Goldilocks, reflation, stagflation, disinflation. No liquid asset owns all four." },
  { term: "Walk-back", group: "Protocol", def: "PMI < 50 AND 2s10s inverted. Both keys. Then contributions route to overnight sterling. Satellites receive zero." },
  { term: "Lock file", group: "Protocol", def: "The only document that authorises AutoInvest. A briefing is not a change log entry. Decision date precedes change date." },
  { term: "Signed sentence", group: "Protocol", def: "One paragraph that names engine weight, caps, look-through equity, planning drawdown. Sign after FOMC. Change the next calendar day." },
  { term: "Classroom seven", group: "Books", def: "30 / 18 / 15 / 14 / 10 / 7 / 6. Teaching object. Jobs, not a personal plan." },
  { term: "Invictus Prime", group: "Books", def: "Prime I: 15-line lock, 7 Sep 2026 23:08. Archived. Prime II is the house lock." },
  { term: "Machine draft", group: "Books", def: "12 Sep 16-line 45% engine pie. Interactive classroom. Unsigned until after 16 Sep FOMC." },
  { term: "Look-through equity", group: "Risk", def: "Direct equity plus equity inside satellites. Draft ~57%. That is the drawdown you actually own." },
  { term: "Gold floor", group: "Risk", def: "Classroom floor 10. Prime prints 9.6. Name the breach. Do not move the floor because a pie looks finished." },
  { term: "INXG probation", group: "Risk", def: "UK RPI is not US CPI. Five-year wreck and 50% drawdown. Sized so a second gilt crisis cannot own the book. Written kill rule." },
  { term: "DBMF gate", group: "Risk", def: "Managed futures. T212 AutoInvest + fractional first. Then VAGS 13.5 → 10.5. Not a sixteenth lock before the gate." },
  { term: "Contribution routing", group: "Protocol", def: "No sales inside the ISA. The 3rd fills floors, skips caps, then underweights. Drift is repaired with new cash." },
  { term: "Size gates", group: "Protocol", def: "FLOT £3k. VHYL £5k. ROLL £10k. Open gate is not an order." },
  { term: "2022 proof", group: "Tape", def: "Inflation exam. Equities and ordinary bonds fell together. Commodities, gold, short TIPS paid. Sixty-forty sat an exam it had not revised for." },
  { term: "BEI vs PCE", group: "Tape", def: "Breakeven is priced inflation. PCE is the print. The gap is the surprise linkers were hired for." },
  { term: "GT30 penalty box", group: "Tape", def: "Green light 5.00. Duration hit 5.40. Thesis is the cut cycle. Do not sell the brigade because a buyback missed." },
  { term: "ICOM $100", group: "Tape", def: "Brent above $100 fires the ICOM tailwind. Overlay becomes co-primary. Cap still applies. Do not enlarge on a session." },
  { term: "Permanently dead", group: "Protocol", def: "D-Prime arithmetic, sector ETFs as weather, FLOT-as-2022-carry, 8% as a plan, a 17th personality beside an existing job." },
  { term: "Six-priority stack", group: "Protocol", def: "Hard cap, walk-back, core drift ±3, satellite drift ±1.5, 75/25 split, satellite collective 20%. Higher priority eats the cash." },
  { term: "VWRP", group: "Ticker", def: "World engine. Residual claims on productivity. Draft 45% / Prime 23.8% / classroom 30%." },
  { term: "ICOM", group: "Ticker", def: "Broad commodities. The only core line paid in both reflation and stagflation. $100 Brent is a tailwind, not a cap rewrite." },
  { term: "SGLN", group: "Ticker", def: "Physical gold. Night watchman. Not CPI. Real-yield tax is short-term; the debt cycle is not." },
  { term: "VAGS", group: "Ticker", def: "GBP-hedged global aggregate. The umbrella. Ugly Sharpe through the worst bond market in 40 years is the job working." },
  { term: "IDTL", group: "Ticker", def: "US 20+ Treasuries. Compressed spring. Stub, not a position." },
  { term: "ITPS", group: "Ticker", def: "US TIPS. Rent-review clause. Can fall when real yields jump even as CPI is hot." },
  { term: "CSH2 / XSTR", group: "Ticker", def: "Overnight sterling. Walk-back reserve. Live pad uses CSH2; machine draft uses XSTR. Same job." },
  { term: "IGLS", group: "Ticker", def: "UK 1–5yr gilts. Ladder rung between cash and VAGS. Prime ticket. Not on the live pad until a lock-file change." },
  { term: "Farmer", group: "Lesson", def: "Wheat, greenhouse, irrigation, barn. He does not earn maximum profit in any single year. He never loses the farm." },
  { term: "Invictus Prime II", group: "Books", def: "Live = lock, 16 Sep 2026 09:46 BST. 17 T212 lines. VAGS + IDTL sold. Gold wrapper IGLN. Copper is WisdomTree metal. Weights only. No sterling total." },
  { term: "The Derrick", group: "Ticker", def: "WNRG — MSCI World Energy. Integrated majors ~50%. Energy equity, not ICOM, not IOGP (98% E&P)." },
  { term: "The Float", group: "Ticker", def: "FLOT — USD floating-rate IG. 1.67y duration. Proposed VAGS replacement. Gate £3k. Open gate is not an order." },
  { term: "Value tilt", group: "Ticker", def: "IWVL — MSCI World Value. The only Prime II add that can absorb VWRP without a new line. Phase 1 at £10k already named it." },
];

export const DRILLS: {
  id: string;
  q: string;
  choices: string[];
  answer: number;
  why: string;
}[] = [
  {
    id: "rooms",
    q: "Growth up, inflation up. Which room?",
    choices: ["Goldilocks", "Reflation", "Stagflation", "Disinflation"],
    answer: 1,
    why: "Both surprises up is reflation. Equities and commodities can coexist. Long nominal duration usually cannot.",
  },
  {
    id: "wrong",
    q: "The design question of this desk is:",
    choices: [
      "What will the economy do next?",
      "Which ticker will win this year?",
      "What do you own if you are wrong?",
      "How do I beat the S&P?",
    ],
    answer: 2,
    why: "All Weather is staffed to survive the year that wins you. The forecast does not have to be perfect. The team has to be complete.",
  },
  {
    id: "walk",
    q: "Walk-back fires when:",
    choices: [
      "PMI < 50",
      "2s10s inverted",
      "PMI < 50 AND 2s10s inverted",
      "VIX > 20",
    ],
    answer: 2,
    why: "Two keys. Tonight neither is live. Observe. Do not pre-position in cash because a single line had a bad session.",
  },
  {
    id: "books",
    q: "Which book is tonight’s T212 pad?",
    choices: [
      "Classroom seven",
      "Live ISA fourteen",
      "Prime fifteen lock",
      "12 Sep machine draft",
    ],
    answer: 1,
    why: "Do not flatten the ticket pad because a briefing was persuasive. Prime is the design lock. The draft is unsigned.",
  },
  {
    id: "2022",
    q: "2022 sat which exam in public?",
    choices: [
      "Growth-shock (60/40 was built for this)",
      "Inflation-shock (equities and ordinary bonds fell together)",
      "Dollar squeeze only",
      "A gold crash",
    ],
    answer: 1,
    why: "That is why gold, commodities and linkers exist. Prime −5.24 versus S&P −18.64 is the proof, not a promise.",
  },
  {
    id: "gold",
    q: "Gold is hired as:",
    choices: [
      "A CPI switch",
      "A night watchman / monetary anchor",
      "A substitute for miners",
      "A replacement for cash",
    ],
    answer: 1,
    why: "Gold is not CPI. Linkers are not gold. Miners are residual claims wearing a metal costume.",
  },
  {
    id: "sell",
    q: "A line is having its weather — it is down. The protocol says:",
    choices: [
      "Sell and rotate into the winner of the year",
      "Do not sell. Partners earn. The 3rd repairs drift.",
      "Move it to cash until PMI recovers",
      "Double it",
    ],
    answer: 1,
    why: "No selling inside the ISA. Every disposal is a compounding engine switched off. Score the sleeve against its contract.",
  },
  {
    id: "debit",
    q: "Until the book is funded, the lever that costs nothing in risk is:",
    choices: [
      "Adding a 17th ticker",
      "Leverage",
      "The monthly debit on the 3rd",
      "Timing FOMC",
    ],
    answer: 2,
    why: "Doubling £200 to £400 at ~8% is close to adding ~2.5pp of return without rewriting the lock.",
  },
  {
    id: "17",
    q: "A 17th personality is:",
    choices: [
      "Diversification",
      "A new forecast wearing an ETF ticker",
      "Required at £10k NAV",
      "How All Weather scales",
    ],
    answer: 1,
    why: "If a job is uncovered, it replaces a line via the lock file. It does not sit beside it.",
  },
  {
    id: "plan",
    q: "Plan around which rate?",
    choices: ["5% stress", "7.5% Bayesian working", "8.18% nine-year history", "10–15% because AI"],
    answer: 0,
    why: "Work from 7.5%. Do not plan around history. Prime cannot honestly promise 10–15% for 30 years.",
  },
  {
    id: "farmer",
    q: "The farmer plants wheat, builds a greenhouse, installs irrigation, and keeps a barn because:",
    choices: [
      "He knows next year’s weather",
      "He wants maximum profit every year",
      "He does not know the weather, and he must not lose the farm",
      "Barns outperform wheat",
    ],
    answer: 2,
    why: "He does not earn maximum profit in any single year. He never loses the farm.",
  },
  {
    id: "lock",
    q: "What authorises an AutoInvest change?",
    choices: [
      "A persuasive briefing",
      "This terminal",
      "A signed lock-file entry, decision date first, change the next calendar day",
      "A green session in ICOM",
    ],
    answer: 2,
    why: "A briefing, an analysis, a conversation — none of these are a change log entry.",
  },
  {
    id: "p2count",
    q: "Prime II claims 16 lines. Living 12 + quiet 5 equals:",
    choices: ["16 — protocol preserved", "17 — the seventeenth line was invented in the table", "15 — Prime lock", "14 — the live ISA"],
    answer: 1,
    why: "Add IWVL, WNRG, FLOT (+3). Exit VAGS, IDTL (−2). Net +1. Count beats slogan.",
  },
  {
    id: "idtl3y",
    q: "IDTL prints a negative three-year annualised return. The classroom says:",
    choices: [
      "Fire it. The data said so.",
      "The fire brigade is hired for 2008 and 2020. A hiking-cycle mark is the job working.",
      "Replace it with INXG at a higher weight",
      "Replace it with WNRG",
    ],
    answer: 1,
    why: "Scoring the stub against 2023–26 is scoring against the winner of the years it was not hired for.",
  },
  {
    id: "wnrg",
    q: "WNRG is hired as:",
    choices: [
      "A second ICOM",
      "Energy equity — integrated majors — a different job from commodity futures and from pure E&P",
      "IOGP under another ticker",
      "A gold substitute",
    ],
    answer: 1,
    why: "ICOM collects the stuff. WNRG collects the companies. IOGP is 98% E&P. Three uniforms is a costume.",
  },
  {
    id: "flot",
    q: "FLOT versus VAGS is:",
    choices: [
      "The same job, cheaper duration",
      "Carry without convexity. A regime call if you fire the umbrella because stock-bond correlation is positive this cycle",
      "Already in the live pad",
      "A tonight ticket after FOMC",
    ],
    answer: 1,
    why: "FLOT 1.67y is not 7–8y quality duration. The gate was £3k. FOMC is a print, not a lock-file.",
  },
  {
    id: "icom100",
    q: "Brent prints $100.95. The protocol says:",
    choices: [
      "Double ICOM tonight",
      "ICOM tailwind is ON. Overlay co-primary. Cap still applies. Do not enlarge on a session.",
      "Sell IDTL because duration is in the penalty box",
      "Walk-back has fired",
    ],
    answer: 1,
    why: "The $100 trigger confirms the job. It does not rewrite the lock. Walk-back still needs PMI < 50 AND an inverted curve.",
  },
  {
    id: "floor",
    q: "Prime gold at 9.6 versus classroom floor 10 means:",
    choices: [
      "The floor moved because the pie looks finished",
      "Name the breach. Do not pretend the floor moved.",
      "Replace gold with miners",
      "The watchman is fired",
    ],
    answer: 1,
    why: "Floors are sentences. If you change the sentence, write it in the lock file. Do not edit it with a pie chart.",
  },
  {
    id: "dbmf",
    q: "DBMF becomes a sixteenth lock when:",
    choices: [
      "Sharpe is 1.47",
      "A briefing is persuasive",
      "T212 AutoInvest + fractional is confirmed, then VAGS 13.5 → 10.5 via the lock file",
      "Brent is over $100",
    ],
    answer: 2,
    why: "A gated candidate is not a line. The gate is operational, then the lock file, then the next contribution date.",
  },
  {
    id: "look",
    q: "Look-through equity in the machine draft is ~57%. That number is:",
    choices: [
      "Decoration",
      "The drawdown you actually own when residual claims are marked down",
      "The same as the 45% VWRP line",
      "A reason to add another satellite",
    ],
    answer: 1,
    why: "Satellites are residual claims in costume. Add them to the engine before you talk about a 10% equity crash.",
  },
];
