import type { Episode } from "@/lib/content";

/** Season 3 · Prime II lock. Education only. */

export const S3: Episode[] = [
  {
    slug: "the-lock",
    code: "15",
    title: "The lock",
    subtitle: "Prime II stamped. Seventeen listed. Pad still fourteen. FOMC is a print.",
    audio: "/audio/ep15.mp3?v=1",
    duration: 272,
    season: "S3",
    jobIds: ["shares", "bonds", "gold", "tips", "commodities", "cash", "long"],
    weatherIds: ["reflation", "stagflation", "disinflation"],
    takeaways: [
      "Prime II is the house lock, 16 Sep 2026, 08:23 BST. Prime I is archived.",
      "Seventeen holdings are listed. Sixteen were claimed. The lock names the hole.",
      "Live T212 is still fourteen lines. AutoInvest earliest 17 Sep. First cash 3 Oct.",
    ],
    chapters: [
      { t: 0, label: "Stamp" },
      { t: 50, label: "Count" },
      { t: 100, label: "Exits" },
      { t: 170, label: "Pad versus lock" },
      { t: 230, label: "Tonight" },
    ],
    transcript: [
      { who: "DESK", text: "ALLWX desk. Episode fifteen. The lock. Sixteenth of September, twenty twenty-six. Invictus Prime Two is stamped at eight twenty-three British Summer Time. That is before tonight’s FOMC print. We name that. A lock is a sentence. A print is weather." },
      { who: "RATES", text: "Prime One, fifteen lines, seventh of September, twenty-three oh eight, is archived. Classroom seven still teaches the rooms. The live ISA is still fourteen lines on Trading Two Twelve. Three clocks. Do not flatten them because a screen was persuasive." },
      { who: "DESK", text: "The slogan said sixteen lines. The table numbers one through seventeen. Living twelve plus quiet five equals seventeen. Add I W V L, W N R G, and FLOT. Exit VAGS and I D T L. Net plus one. The lock names the hole instead of pretending the slogan won." },
      { who: "RATES", text: "Living eighty point five. Quiet nineteen point five. Engine stays forty-five: Vanguard All-World thirty-eight, world value seven. Irrigation eight. Barn eight. Surfer four, still gated. Derrick three. Defence three. Semis two and a half. Industrials two. Healthcare two. Copper two. Uranium one." },
      { who: "DESK", text: "Quiet: TIPS six. The float six. London thermometer three. The tin three. Short gilts one and a half. VAGS is gone on purpose. The long spring is starved of new cash, not sold. No sales inside the ISA. Contributions are the only tool." },
      { who: "RATES", text: "I D T L printed a negative three-year. The proposal fired it for that mark. The classroom hired the fire brigade for two thousand eight and two thousand twenty. A hiking-cycle mark is the job working. The lock accepts the trade-off and scores deflation C. Named, not hidden." },
      { who: "DESK", text: "VAGS to FLOT is not the same job cheaper. Seven to eight years of quality duration versus a one point six seven year dollar floater. Removing the umbrella because stock-bond correlation is positive this cycle is a regime call wearing a repair costume. Deflation C follows." },
      { who: "RATES", text: "Gold at eight is two points under the classroom floor of ten. Named. I N X G at three is still probation. The five-year wreck and the fifty percent drawdown are still the veto. Kill rule stands. Raising a probation line is not a cleared gate." },
      { who: "DESK", text: "D B M F at four is a target. The gate is operational: AutoInvest plus fractional on the platform. FLOT’s gate is listed on the platform. Open gate is not an order. Walk-back still needs both keys: P M I under fifty, and two-tens inverted. Tonight both are clear." },
      { who: "RATES", text: "Decision date is today. Change date is the seventeenth. First cash is the third of October. The pad does not move because we stamped a sentence before a meeting. If walk-back fires tonight, the whole upgrade queue pauses. The circuit breaker sits above the lock." },
      { who: "DESK", text: "Third of October. Semis first, because the signed pad said so. Remainder to the derrick at one percent if Brent holds seventy-five pounds and commodities sit inside two hundred basis points of eight. New lines enter at one percent. Size is the risk management." },
      { who: "RATES", text: "November: float begins if the two-year gilt stays above four and FLOT is listed. Stop reinvesting VAGS income. Value at one percent only if the engine is still at or above thirty-eight. Recency is the enemy of the third. Forty-three percent year-to-date is not a 1970s proof." },
      { who: "DESK", text: "What you own if you are wrong is still the only design question. Prime Two is more living, less quiet, no long nominal, a named energy-equity line. It will look clever in overlay weather. It will look unemployed in a demand crash. That is the sentence you just signed." },
      { who: "RATES", text: "Fifteen was Prime One. Seventeen is Prime Two. Fourteen is the pad. Seven is the classroom. FOMC at nineteen hundred. Observe. Do not rebuild. ALLWX desk. Out." },
    ],
  },
  {
    slug: "the-derrick",
    code: "16",
    title: "The derrick",
    subtitle: "WNRG is the structure above the well. IOGP is the well. ICOM is the stuff.",
    audio: "/audio/ep16.mp3?v=1",
    duration: 227,
    season: "S3",
    jobIds: ["commodities", "shares", "gold"],
    weatherIds: ["stagflation", "reflation", "disinflation"],
    takeaways: [
      "ICOM collects the commodity. WNRG collects integrated majors. IOGP is 98% E&P.",
      "Almost no holdings overlap. Two uniforms is already a costume. Three is a parade.",
      "First add, if any, is WNRG at 1%. IOGP stays on the watch list until Brent is a $120 weather.",
    ],
    chapters: [
      { t: 0, label: "Three jobs" },
      { t: 38, label: "Sub-sectors" },
      { t: 85, label: "When each wins" },
      { t: 140, label: "Recency" },
      { t: 190, label: "Size" },
    ],
    transcript: [
      { who: "DESK", text: "ALLWX desk. Episode sixteen. The derrick. The farm had irrigation and no energy equity. That gap is real. The loud three-year number is also real. They are not the same fact." },
      { who: "RATES", text: "Three employees who share a headline and not a cash-flow. ICOM is a diversified commodity swap. It collects the stuff. W N R G is MSCI World Energy. Half of it is integrated oils: Exxon, Chevron, Shell, Total, BP. I O G P is ninety-eight percent exploration and production. The well, not the refinery." },
      { who: "DESK", text: "Sub-sectors. W N R G: integrated fifty, E and P nineteen, midstream fourteen, refining ten, services five. I O G P: E and P ninety-eight, midstream one. Across the top ten, two names overlap: Conoco and Canadian Natural. The rest of the uniforms are different companies." },
      { who: "RATES", text: "Oil beta is medium on the derrick and high on the well. Expense is thirty basis points versus fifty-five. Assets six hundred million versus four hundred and fifty. Built slowly on the third, liquidity matters. The cheaper, larger, more diversified line is the farm line." },
      { who: "DESK", text: "The well wins a spike. Deep stagflation, nineteen seventy-three to eighty. A supply shock that stays. Operating leverage on pure upstream is the point. If Brent is a hundred and twenty weather, not a hundred session, the watch list becomes a conversation." },
      { who: "RATES", text: "The derrick wins chop. Downstream cushions. Shell’s dividend breakeven near twenty-eight dollars is not an E and P lottery ticket. European majors tilt gas. Regime uncertainty is the base case. The farm already owns the commodity through ICOM. Doubling raw oil beta is two employees for one surprise." },
      { who: "DESK", text: "Look-through. Vanguard All-World already holds about four percent energy. At a forty-five engine that is one point eight of the farm. Not enough to call the derrick redundant. Enough to call a second energy E T F a costume." },
      { who: "RATES", text: "Twenty twenty. Energy equity minus forty. At three percent of the farm that is eighty to one hundred and twenty basis points. Survivable. Still a residual claim. Still rhymes with the engine in a growth crash. ICOM can also fall in a demand shock. They are not a hedge for each other on that day." },
      { who: "DESK", text: "Miners are not the barn. G D X adds equity beta to the watchman. The classroom already fired that substitution. Junior miners are beta on beta. Clean energy at two point eight annualised and sixty-five basis points of cost is a theme, not a weather." },
      { who: "RATES", text: "Recency. Forty-three percent year-to-date on W N R G is the supercycle showing up in a sample. The protocol’s answer is the same as the semi trim: size is the risk management. A new line enters at one percent. It earns three over six to nine months of the third. That is not slowness. That is the hand." },
      { who: "DESK", text: "Brent above seventy-five pounds is a precondition, not a forecast. Commodities inside two hundred basis points of eight so the derrick is incremental. Semis bought first because the signed pad said so. Walk-back pauses the lot." },
      { who: "RATES", text: "Suggested farm name: the derrick. The structure that sits above the well, not the well itself. I O G P stays on the watch list. Holding both is a seventeenth personality the protocol does not permit. ALLWX desk. Out." },
    ],
  },
  {
    slug: "the-universe",
    code: "17",
    title: "The universe",
    subtitle: "Five filters. Rank is a screen, not a ticket. Recency is the enemy of the third.",
    audio: "/audio/ep17.mp3?v=1",
    duration: 225,
    season: "S3",
    jobIds: ["shares", "bonds", "gold", "cash"],
    weatherIds: ["goldilocks", "reflation", "stagflation", "disinflation"],
    takeaways: [
      "A candidate needs a three-year track, two weathers, a gap or a replacement, and no seventeenth personality.",
      "IWVL absorbing VWRP is the only add that does not invent a line.",
      "FLOT is a gate at listed-on-platform and three thousand NAV. Open gate is not an order.",
    ],
    chapters: [
      { t: 0, label: "Filters" },
      { t: 38, label: "Gaps" },
      { t: 85, label: "Factors" },
      { t: 130, label: "Quiet farm" },
      { t: 180, label: "Kills" },
    ],
    transcript: [
      { who: "DESK", text: "ALLWX desk. Episode seventeen. The universe. Thirty tickers. Five filters. The farm has not yet considered these. That is not the same as hiring them." },
      { who: "RATES", text: "Filter one: three-year track. Post-twenty twenty-three launches have no stress test. Filter two: earn in at least two weathers. Filter three: fill a gap or replace a line. Filter four: no seventeenth personality. Assessed as replacement or absorption. Not addition." },
      { who: "DESK", text: "Gaps. No dedicated energy equity — that is the derrick, last episode. No explicit E M tilt. Vanguard already holds emerging at about twelve of the engine. I E E M at eighteen basis points is cheap and a second line unless it replaces. Equal-weight S and P is United States only. It is not a world engine." },
      { who: "RATES", text: "Infrastructure at sixty-five basis points is inflation-linked revenue, not a linker. Global real estate is next-regime, not this overlay. Clean energy dies on a weak three-year and a high cost. Physical gold from a second provider duplicates the barn. Correctly killed." },
      { who: "DESK", text: "Factors. Value, quality, low vol, small, dividend, momentum. All listed in London. Value is the paper trail. World value, thirty-five annualised over three years in a high-rate sample. Cash flows front-loaded. Less duration than growth. Phase one at ten thousand already named it. Absorption of the engine. Not a new room." },
      { who: "RATES", text: "Momentum rhymes with the surfer and with last year’s winner. Two uniforms. High dividend is a five-thousand size gate, not a third-of-October ticker. Minimum volatility is a quiet-farm candidate, not an engine. Multi-factor is fine and dominated by value on this tape." },
      { who: "DESK", text: "Quiet farm. VAGS is seven to eight years of duration in a positive stock-bond correlation. FLOT yields four point one seven with one point six seven years. That is the honest argument. The dishonest one was twenty twenty-two plus thirteen point nine in sterling, which was dollar, not carry. The gate was three thousand NAV. Still is." },
      { who: "RATES", text: "U S F R is the government-grade fallback if FLOT is not listed. Short high-yield is credit in the quiet farm — equity wearing a coupon. Euro ultrashort is a currency mismatch for a sterling I S A. Long sterling corporates failed their own duration test. I G L S is already held and validated as the short gilt rung." },
      { who: "DESK", text: "Gold miners complement the barn and add equity risk the barn does not carry. Junior miners are too loud. Efficient core at one hundred and fifty percent notional is leverage a retail I S A was not built to hold. Rank is a screen. Screens do not AutoInvest." },
      { who: "RATES", text: "Priority if the protocol allows one absorption: world value from the engine. Priority if it allows one named hole: the derrick at one percent. Priority if it allows one replacement: FLOT for VAGS by drift, gated. All three at once is how you invent the seventeenth line while quoting the rule against it." },
      { who: "DESK", text: "Recency is the enemy of the third. The strongest three-year numbers in the screen are energy and value in a sample that paid energy and value. The farm is staffed for four rooms. A screen is how you name gaps. A lock is how you refuse to chase them. ALLWX desk. Out." },
    ],
  },
  {
    slug: "the-third",
    code: "18",
    title: "The third",
    subtitle: "Gates, walk-back, FOMC, the only action date. Measured, not slow.",
    audio: "/audio/ep18.mp3?v=1",
    duration: 215,
    season: "S3",
    jobIds: ["cash", "shares", "bonds", "commodities"],
    weatherIds: ["goldilocks", "reflation", "stagflation", "disinflation"],
    takeaways: [
      "Walk-back overrides the whole queue. Two keys. Tonight both are clear.",
      "3 Oct: SMGB first, then WNRG 1% if Brent > £75 and ICOM inside 200bp of 8%.",
      "Measured is active sequencing with preconditions. Slow is drift without a hand. Fast is recency.",
    ],
    chapters: [
      { t: 0, label: "Tonight" },
      { t: 40, label: "3 Oct" },
      { t: 90, label: "Nov–Dec" },
      { t: 140, label: "Measured" },
      { t: 180, label: "Fridge" },
    ],
    transcript: [
      { who: "DESK", text: "ALLWX desk. Episode eighteen. The third. Weight changes run on a monthly clock. New lines run on a multi-year clock. The lock is stamped. The pad has not moved. Tonight is a meeting. The third of October is an action date." },
      { who: "RATES", text: "Gate zero. FOMC at nineteen hundred British Summer Time. A twenty-five hike is mostly priced and does not rewrite jobs. A surprise hold or hawkish dots raise the urgency of the float and the starvation of the long spring. Still not a tonight ticket. Bank of England Thursday. Same rule." },
      { who: "DESK", text: "Walk-back sits above the lock. P M I fifty-four point six. Two-tens positive. Both keys clear. If either key flips before a gate, the upgrade pauses. The circuit breaker exists so the contribution protocol does not buy into a winter with a summer map." },
      { who: "RATES", text: "Third of October. Semiconductors first. The signed pad is not overridden by a new lock. Remainder to the derrick at one percent if Brent is above seventy-five pounds — it is — and commodities are inside two hundred basis points of eight — they are. If Brent fails, delay the derrick. Do not invent a seventeenth line to spend the cash." },
      { who: "DESK", text: "November. VAGS to FLOT by drift. Stop reinvesting the greenhouse coupon. Point new cash at the float if the two-year gilt is above four and the name is listed. If the platform cannot list it, U S F R is the fallback, not a guess in chat. Value at one percent only if the engine is still at or above thirty-eight." },
      { who: "RATES", text: "December onward. Derrick toward three. Value toward seven by mid twenty twenty-seven. The long spring receives no new cash. The thermometer absorbs. If value falls more than fifteen from here before three and a half percent, slow the pace. Dollar-cost averaging is the hand, not a dare." },
      { who: "DESK", text: "Measured is not slow. Slow is leaving VAGS and I D T L funded for another year because the meeting is scary. Measured is sequencing with preconditions. Fast is sizing the derrick at three on the first third because year-to-date is forty-three. Recency is the enemy. Size is the risk management." },
      { who: "RATES", text: "Two reasons not to be slow: the quiet farm is in the wrong duration for this correlation, and the named gaps are working in this weather. Two reasons not to be fast: the seventeenth line, and the sample. The protocol already answered the semi-trim temptation. Use the same answer." },
      { who: "DESK", text: "Human capital is still a growth asset. Sequence risk still arrives early if you check the book between contribution dates. Twenty-three by five equity hours raise overnight gaps. The rule does not change. The bay exists so you do not have to sell the engine." },
      { who: "RATES", text: "Fridge. What you own if you are wrong. Four rooms. Jobs, not stories. Gold is not C P I. The derrick is not irrigation. The float is not the umbrella. The long spring is hired for two thousand eight. Walk-back two keys. The third is the only action date. Pain plus reflection equals progress." },
      { who: "DESK", text: "Seventeen listed. Fourteen on the pad. Seven in the classroom. Prime Two is the lock. FOMC tonight. Observe. File the if-then. Do not rebuild. ALLWX desk. Out." },
    ],
  },
];
