/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DebateRouteImport } from './routes/debate'
import { Route as HouseRouteImport } from './routes/house'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PieRouteImport } from './routes/pie'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as StudyRouteImport } from './routes/study'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as WeathersRouteImport } from './routes/weathers'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnAtlasRouteImport } from './routes/learn.atlas'
import { Route as LearnCompareRouteImport } from './routes/learn.compare'
import { Route as LearnDecideRouteImport } from './routes/learn.decide'
import { Route as LearnDerrickRouteImport } from './routes/learn.derrick'
import { Route as LearnLibraryRouteImport } from './routes/learn.library'
import { Route as LearnLockRouteImport } from './routes/learn.lock'
import { Route as LearnMachineRouteImport } from './routes/learn.machine'
import { Route as LearnPathRouteImport } from './routes/learn.path'
import { Route as LearnPrime2RouteImport } from './routes/learn.prime2'
import { Route as LearnQuizRouteImport } from './routes/learn.quiz'
import { Route as LearnUniverseRouteImport } from './routes/learn.universe'
import { Route as LearnYearsRouteImport } from './routes/learn.years'
import { Route as ListenIndexRouteImport } from './routes/listen.index'
import { Route as ListenSlugRouteImport } from './routes/listen.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DebateRoute = DebateRouteImport.update({
  id: '/debate',
  path: '/debate',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PieRoute = PieRouteImport.update({
  id: '/pie',
  path: '/pie',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const WeathersRoute = WeathersRouteImport.update({
  id: '/weathers',
  path: '/weathers',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAtlasRoute = LearnAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCompareRoute = LearnCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LearnRoute,
} as any)
const LearnDecideRoute = LearnDecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => LearnRoute,
} as any)
const LearnDerrickRoute = LearnDerrickRouteImport.update({
  id: '/derrick',
  path: '/derrick',
  getParentRoute: () => LearnRoute,
} as any)
const LearnLibraryRoute = LearnLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => LearnRoute,
} as any)
const LearnLockRoute = LearnLockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => LearnRoute,
} as any)
const LearnMachineRoute = LearnMachineRouteImport.update({
  id: '/machine',
  path: '/machine',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPathRoute = LearnPathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPrime2Route = LearnPrime2RouteImport.update({
  id: '/prime2',
  path: '/prime2',
  getParentRoute: () => LearnRoute,
} as any)
const LearnQuizRoute = LearnQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => LearnRoute,
} as any)
const LearnUniverseRoute = LearnUniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => LearnRoute,
} as any)
const LearnYearsRoute = LearnYearsRouteImport.update({
  id: '/years',
  path: '/years',
  getParentRoute: () => LearnRoute,
} as any)
const ListenIndexRoute = ListenIndexRouteImport.update({
  id: '/listen/',
  path: '/listen/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenSlugRoute = ListenSlugRouteImport.update({
  id: '/listen/$slug',
  path: '/listen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/debate': typeof DebateRoute
  '/house': typeof HouseRoute
  '/jobs': typeof JobsRouteWithChildren
  '/lab': typeof LabRoute
  '/learn': typeof LearnRouteWithChildren
  '/pie': typeof PieRoute
  '/rules': typeof RulesRoute
  '/study': typeof StudyRoute
  '/tape': typeof TapeRoute
  '/weathers': typeof WeathersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/atlas': typeof LearnAtlasRoute
  '/learn/compare': typeof LearnCompareRoute
  '/learn/decide': typeof LearnDecideRoute
  '/learn/derrick': typeof LearnDerrickRoute
  '/learn/library': typeof LearnLibraryRoute
  '/learn/lock': typeof LearnLockRoute
  '/learn/machine': typeof LearnMachineRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/prime2': typeof LearnPrime2Route
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/universe': typeof LearnUniverseRoute
  '/learn/years': typeof LearnYearsRoute
  '/listen/$slug': typeof ListenSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/listen/': typeof ListenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/debate': typeof DebateRoute
  '/house': typeof HouseRoute
  '/lab': typeof LabRoute
  '/pie': typeof PieRoute
  '/rules': typeof RulesRoute
  '/study': typeof StudyRoute
  '/tape': typeof TapeRoute
  '/weathers': typeof WeathersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/atlas': typeof LearnAtlasRoute
  '/learn/compare': typeof LearnCompareRoute
  '/learn/decide': typeof LearnDecideRoute
  '/learn/derrick': typeof LearnDerrickRoute
  '/learn/library': typeof LearnLibraryRoute
  '/learn/lock': typeof LearnLockRoute
  '/learn/machine': typeof LearnMachineRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/prime2': typeof LearnPrime2Route
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/universe': typeof LearnUniverseRoute
  '/learn/years': typeof LearnYearsRoute
  '/listen/$slug': typeof ListenSlugRoute
  '/jobs': typeof JobsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/listen': typeof ListenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/debate': typeof DebateRoute
  '/house': typeof HouseRoute
  '/jobs': typeof JobsRouteWithChildren
  '/lab': typeof LabRoute
  '/learn': typeof LearnRouteWithChildren
  '/pie': typeof PieRoute
  '/rules': typeof RulesRoute
  '/study': typeof StudyRoute
  '/tape': typeof TapeRoute
  '/weathers': typeof WeathersRoute
  '/jobs/$id': typeof JobsIdRoute
  '/learn/atlas': typeof LearnAtlasRoute
  '/learn/compare': typeof LearnCompareRoute
  '/learn/decide': typeof LearnDecideRoute
  '/learn/derrick': typeof LearnDerrickRoute
  '/learn/library': typeof LearnLibraryRoute
  '/learn/lock': typeof LearnLockRoute
  '/learn/machine': typeof LearnMachineRoute
  '/learn/path': typeof LearnPathRoute
  '/learn/prime2': typeof LearnPrime2Route
  '/learn/quiz': typeof LearnQuizRoute
  '/learn/universe': typeof LearnUniverseRoute
  '/learn/years': typeof LearnYearsRoute
  '/listen/$slug': typeof ListenSlugRoute
  '/jobs/': typeof JobsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/listen/': typeof ListenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cases'
    | '/debate'
    | '/house'
    | '/jobs'
    | '/lab'
    | '/learn'
    | '/pie'
    | '/rules'
    | '/study'
    | '/tape'
    | '/weathers'
    | '/jobs/$id'
    | '/learn/atlas'
    | '/learn/compare'
    | '/learn/decide'
    | '/learn/derrick'
    | '/learn/library'
    | '/learn/lock'
    | '/learn/machine'
    | '/learn/path'
    | '/learn/prime2'
    | '/learn/quiz'
    | '/learn/universe'
    | '/learn/years'
    | '/listen/$slug'
    | '/jobs/'
    | '/learn/'
    | '/listen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cases'
    | '/debate'
    | '/house'
    | '/lab'
    | '/pie'
    | '/rules'
    | '/study'
    | '/tape'
    | '/weathers'
    | '/jobs/$id'
    | '/learn/atlas'
    | '/learn/compare'
    | '/learn/decide'
    | '/learn/derrick'
    | '/learn/library'
    | '/learn/lock'
    | '/learn/machine'
    | '/learn/path'
    | '/learn/prime2'
    | '/learn/quiz'
    | '/learn/universe'
    | '/learn/years'
    | '/listen/$slug'
    | '/jobs'
    | '/learn'
    | '/listen'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/debate'
    | '/house'
    | '/jobs'
    | '/lab'
    | '/learn'
    | '/pie'
    | '/rules'
    | '/study'
    | '/tape'
    | '/weathers'
    | '/jobs/$id'
    | '/learn/atlas'
    | '/learn/compare'
    | '/learn/decide'
    | '/learn/derrick'
    | '/learn/library'
    | '/learn/lock'
    | '/learn/machine'
    | '/learn/path'
    | '/learn/prime2'
    | '/learn/quiz'
    | '/learn/universe'
    | '/learn/years'
    | '/listen/$slug'
    | '/jobs/'
    | '/learn/'
    | '/listen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  DebateRoute: typeof DebateRoute
  HouseRoute: typeof HouseRoute
  JobsRoute: typeof JobsRouteWithChildren
  LabRoute: typeof LabRoute
  LearnRoute: typeof LearnRouteWithChildren
  PieRoute: typeof PieRoute
  RulesRoute: typeof RulesRoute
  StudyRoute: typeof StudyRoute
  TapeRoute: typeof TapeRoute
  WeathersRoute: typeof WeathersRoute
  ListenSlugRoute: typeof ListenSlugRoute
  ListenIndexRoute: typeof ListenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debate': {
      id: '/debate'
      path: '/debate'
      fullPath: '/debate'
      preLoaderRoute: typeof DebateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pie': {
      id: '/pie'
      path: '/pie'
      fullPath: '/pie'
      preLoaderRoute: typeof PieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weathers': {
      id: '/weathers'
      path: '/weathers'
      fullPath: '/weathers'
      preLoaderRoute: typeof WeathersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/atlas': {
      id: '/learn/atlas'
      path: '/atlas'
      fullPath: '/learn/atlas'
      preLoaderRoute: typeof LearnAtlasRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/compare': {
      id: '/learn/compare'
      path: '/compare'
      fullPath: '/learn/compare'
      preLoaderRoute: typeof LearnCompareRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/decide': {
      id: '/learn/decide'
      path: '/decide'
      fullPath: '/learn/decide'
      preLoaderRoute: typeof LearnDecideRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/derrick': {
      id: '/learn/derrick'
      path: '/derrick'
      fullPath: '/learn/derrick'
      preLoaderRoute: typeof LearnDerrickRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/library': {
      id: '/learn/library'
      path: '/library'
      fullPath: '/learn/library'
      preLoaderRoute: typeof LearnLibraryRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/lock': {
      id: '/learn/lock'
      path: '/lock'
      fullPath: '/learn/lock'
      preLoaderRoute: typeof LearnLockRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/machine': {
      id: '/learn/machine'
      path: '/machine'
      fullPath: '/learn/machine'
      preLoaderRoute: typeof LearnMachineRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/path': {
      id: '/learn/path'
      path: '/path'
      fullPath: '/learn/path'
      preLoaderRoute: typeof LearnPathRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/prime2': {
      id: '/learn/prime2'
      path: '/prime2'
      fullPath: '/learn/prime2'
      preLoaderRoute: typeof LearnPrime2RouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/quiz': {
      id: '/learn/quiz'
      path: '/quiz'
      fullPath: '/learn/quiz'
      preLoaderRoute: typeof LearnQuizRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/universe': {
      id: '/learn/universe'
      path: '/universe'
      fullPath: '/learn/universe'
      preLoaderRoute: typeof LearnUniverseRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/years': {
      id: '/learn/years'
      path: '/years'
      fullPath: '/learn/years'
      preLoaderRoute: typeof LearnYearsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/listen/': {
      id: '/listen/'
      path: '/listen'
      fullPath: '/listen/'
      preLoaderRoute: typeof ListenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen/$slug': {
      id: '/listen/$slug'
      path: '/listen/$slug'
      fullPath: '/listen/$slug'
      preLoaderRoute: typeof ListenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface LearnRouteChildren {
  LearnAtlasRoute: typeof LearnAtlasRoute
  LearnCompareRoute: typeof LearnCompareRoute
  LearnDecideRoute: typeof LearnDecideRoute
  LearnDerrickRoute: typeof LearnDerrickRoute
  LearnLibraryRoute: typeof LearnLibraryRoute
  LearnLockRoute: typeof LearnLockRoute
  LearnMachineRoute: typeof LearnMachineRoute
  LearnPathRoute: typeof LearnPathRoute
  LearnPrime2Route: typeof LearnPrime2Route
  LearnQuizRoute: typeof LearnQuizRoute
  LearnUniverseRoute: typeof LearnUniverseRoute
  LearnYearsRoute: typeof LearnYearsRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnAtlasRoute: LearnAtlasRoute,
  LearnCompareRoute: LearnCompareRoute,
  LearnDecideRoute: LearnDecideRoute,
  LearnDerrickRoute: LearnDerrickRoute,
  LearnLibraryRoute: LearnLibraryRoute,
  LearnLockRoute: LearnLockRoute,
  LearnMachineRoute: LearnMachineRoute,
  LearnPathRoute: LearnPathRoute,
  LearnPrime2Route: LearnPrime2Route,
  LearnQuizRoute: LearnQuizRoute,
  LearnUniverseRoute: LearnUniverseRoute,
  LearnYearsRoute: LearnYearsRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  DebateRoute: DebateRoute,
  HouseRoute: HouseRoute,
  JobsRoute: JobsRouteWithChildren,
  LabRoute: LabRoute,
  LearnRoute: LearnRouteWithChildren,
  PieRoute: PieRoute,
  RulesRoute: RulesRoute,
  StudyRoute: StudyRoute,
  TapeRoute: TapeRoute,
  WeathersRoute: WeathersRoute,
  ListenSlugRoute: ListenSlugRoute,
  ListenIndexRoute: ListenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
